#!/bin/bash
# Blocks writes to build artifacts, binary files, and dependency directories in a TS/JS project.
# Used as a PreToolUse hook for Edit|Write operations.
# Exit 2 = block the action. Exit 0 = allow.

# Requires jq for JSON parsing — fail closed if missing
if ! command -v jq >/dev/null 2>&1; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"jq is required for file protection hooks but is not installed.\"}}"
  exit 2
fi

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Block dependency and build output directories
case "$FILE_PATH" in
  node_modules/*|*/node_modules/*)
    REASON="Cannot write into node_modules/ — managed by your package manager." ;;
  dist/*|*/dist/*)
    REASON="Cannot write into dist/ — generated by the build." ;;
  build/*|*/build/*)
    REASON="Cannot write into build/ — generated by the build." ;;
  .next/*|*/.next/*)
    REASON="Cannot write into .next/ — generated by Next.js." ;;
  .nuxt/*|*/.nuxt/*)
    REASON="Cannot write into .nuxt/ — generated by Nuxt." ;;
  .output/*|*/.output/*)
    REASON="Cannot write into .output/ — generated by Nitro/Nuxt." ;;
  .svelte-kit/*|*/.svelte-kit/*)
    REASON="Cannot write into .svelte-kit/ — generated by SvelteKit." ;;
  .turbo/*|*/.turbo/*)
    REASON="Cannot write into .turbo/ — Turborepo cache." ;;
  .cache/*|*/.cache/*)
    REASON="Cannot write into .cache/ — framework cache directory." ;;
  coverage/*|*/coverage/*)
    REASON="Cannot write into coverage/ — generated by the test runner." ;;
  .parcel-cache/*|*/.parcel-cache/*)
    REASON="Cannot write into .parcel-cache/ — Parcel cache." ;;
  *)
    REASON="" ;;
esac

if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

# Block binary and archive file extensions
BASENAME=$(basename "$FILE_PATH")
case "$BASENAME" in
  *.wasm|*.so|*.dylib|*.dll|*.exe|*.o|*.a)
    REASON="Cannot write binary files — these should be compiled, not hand-written." ;;
  *.zip|*.tar|*.tar.gz|*.tar.bz2|*.tgz|*.rar|*.7z|*.bun.lockb)
    REASON="Cannot write archive or binary lockfile." ;;
  *.mp4|*.mov|*.avi|*.mkv|*.mp3|*.wav|*.flac)
    REASON="Cannot write media files — add these manually outside Claude Code." ;;
  *.map)
    REASON="Cannot write .map files — these are generated source maps." ;;
  *.min.js|*.min.css)
    REASON="Cannot write minified files — these are build outputs." ;;
esac

if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

exit 0
