#!/bin/bash
# Blocks writes to build artifacts, caches, and virtual environments.
# Used as a PreToolUse hook for Edit|Write operations.
# Exit 2 = block the action. Exit 0 = allow.

# Requires jq for JSON parsing — fail closed if missing
if ! command -v jq >/dev/null 2>&1; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"jq is required for file protection hooks but is not installed.\"}}"
  exit 2
fi

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Block generated and cached directories
case "$FILE_PATH" in
  __pycache__/*|*/__pycache__/*)
    REASON="Cannot write into __pycache__/ — these are generated by Python." ;;
  .venv/*|*/.venv/*)
    REASON="Cannot write into .venv/ — managed by the package manager." ;;
  venv/*|*/venv/*)
    REASON="Cannot write into venv/ — managed by the package manager." ;;
  .mypy_cache/*|*/.mypy_cache/*)
    REASON="Cannot write into .mypy_cache/ — generated by mypy." ;;
  .ruff_cache/*|*/.ruff_cache/*)
    REASON="Cannot write into .ruff_cache/ — generated by ruff." ;;
  .pytest_cache/*|*/.pytest_cache/*)
    REASON="Cannot write into .pytest_cache/ — generated by pytest." ;;
  dist/*|*/dist/*)
    REASON="Cannot write into dist/ — generated by the build system." ;;
  *.egg-info/*|*/*.egg-info/*)
    REASON="Cannot write into *.egg-info/ — generated by setuptools." ;;
  htmlcov/*|*/htmlcov/*)
    REASON="Cannot write into htmlcov/ — generated by coverage." ;;
  *)
    REASON="" ;;
esac

if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

# Block binary and archive file extensions
BASENAME=$(basename "$FILE_PATH")
case "$BASENAME" in
  *.wasm|*.so|*.dylib|*.dll|*.exe|*.o|*.a)
    REASON="Cannot write binary files — these should be compiled, not hand-written." ;;
  *.zip|*.tar|*.tar.gz|*.tar.bz2|*.tgz|*.rar|*.7z)
    REASON="Cannot write archive files." ;;
  *.pyc|*.pyo)
    REASON="Cannot write .pyc/.pyo files — these are generated by Python." ;;
esac

if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

exit 0
