#!/bin/bash
# Blocks writes to build artifacts and generated directories.
# Used as a PreToolUse hook for Edit|Write operations.
# Exit 2 = block the action. Exit 0 = allow.
#
# TODO: Customize blocked directories for go

if ! command -v jq >/dev/null 2>&1; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"jq is required for file protection hooks but is not installed.\"}}"
  exit 2
fi

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# TODO: Add stack-specific build output directories
case "$FILE_PATH" in
  # Example patterns — customize for your stack:
  # node_modules/*|*/node_modules/*) REASON="Managed by package manager" ;;
  # dist/*|*/dist/*) REASON="Generated by build" ;;
  # _build/*|*/_build/*) REASON="Generated by compiler" ;;
  # target/*|*/target/*) REASON="Generated by compiler" ;;
  *) REASON="" ;;
esac

if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

exit 0
