#!/bin/bash
# Blocks writes to build artifacts and generated directories.
# Used as a PreToolUse hook for Edit|Write operations.
# Exit 2 = block the action. Exit 0 = allow.

if ! command -v jq >/dev/null 2>&1; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"jq is required for file protection hooks but is not installed.\"}}"
  exit 2
fi

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

REASON=""

case "$FILE_PATH" in
  node_modules/*|*/node_modules/*) REASON="Managed by package manager — do not edit." ;;
  dist/*|*/dist/*) REASON="Generated by build — do not edit." ;;
  coverage/*|*/coverage/*) REASON="Generated by test runner — do not edit." ;;
  .turbo/*|*/.turbo/*) REASON="Turborepo cache — do not edit." ;;
esac

if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

exit 0
